export const images: { [key: string]: string } = {
    'Pop-Happy': 'assert/images/pop-happy.jpg',
    'Pop-Sad': 'assert/images/pop-sad.jpg',
    'Pop-Energetic': 'assert/images/pop-energetic.jpg',
    'Pop-Relaxed': 'assert/images/pop-relaxed.jpg',
    'Pop-Melancholic': 'assert/images/pop-melancholic.jpg',
    'Pop-Excited': 'assert/images/pop-excited.jpg',
    'Pop-Calm': 'assert/images/pop-calm.jpg',
    
    'Rock-Happy': 'assert/images/rock-happy.jpg',
    'Rock-Sad': 'assert/images/rock-sad.jpg',
    'Rock-Energetic': 'assert/images/rock-energetic.jpg',
    'Rock-Relaxed': 'assert/images/rock-relaxed.jpg',
    'Rock-Melancholic': 'assert/images/rock-melancholic.jpg',
    'Rock-Excited': 'assert/images/rock-excited.jpg',
    'Rock-Calm': 'assert/images/rock-calm.jpg',
    
    'Jazz-Happy': 'assert/images/jazz-happy.jpg',
    'Jazz-Sad': 'assert/images/jazz-sad.jpg',
    'Jazz-Energetic': 'assert/images/jazz-energetic.jpg',
    'Jazz-Relaxed': 'assert/images/jazz-relaxed.jpg',
    'Jazz-Melancholic': 'assert/images/jazz-melancholic.jpg',
    'Jazz-Excited': 'assert/images/jazz-excited.jpg',
    'Jazz-Calm': 'assert/images/jazz-calm.jpg',
  
    'Classical-Happy': 'assert/images/classical-happy.jpg',
    'Classical-Sad': 'assert/images/classical-sad.jpg',
    'Classical-Energetic': 'assert/images/classical-energetic.jpg',
    'Classical-Relaxed': 'assert/images/classical-relaxed.jpg',
    'Classical-Melancholic': 'assert/images/classical-melancholic.jpg',
    'Classical-Excited': 'assert/images/classical-excited.jpg',
    'Classical-Calm': 'assert/images/classical-calm.jpg',
  
    'Hip Hop-Happy': 'assert/images/hiphop-happy.jpg',
    'Hip Hop-Sad': 'assert/images/hiphop-sad.jpg',
    'Hip Hop-Energetic': 'assert/images/hiphop-energetic.jpg',
    'Hip Hop-Relaxed': 'assert/images/hiphop-relaxed.jpg',
    'Hip Hop-Melancholic': 'assert/images/hiphop-melancholic.jpg',
    'Hip Hop-Excited': 'assert/images/hiphop-excited.jpg',
    'Hip Hop-Calm': 'assert/images/hiphop-calm.jpg',
  
    'Electronic-Happy': 'assert/images/electronic-happy.jpg',
    'Electronic-Sad': 'assert/images/electronic-sad.jpg',
    'Electronic-Energetic': 'assert/images/electronic-energetic.jpg',
    'Electronic-Relaxed': 'assert/images/electronic-relaxed.jpg',
    'Electronic-Melancholic': 'assert/images/electronic-melancholic.jpg',
    'Electronic-Excited': 'assert/images/electronic-excited.jpg',
    'Electronic-Calm': 'assert/images/electronic-calm.jpg',
  
    'Country-Happy': 'assert/images/country-happy.jpg',
    'Country-Sad': 'assert/images/country-sad.jpg',
    'Country-Energetic': 'assert/images/country-energetic.jpg',
    'Country-Relaxed': 'assert/images/country-relaxed.jpg',
    'Country-Melancholic': 'assert/images/country-melancholic.jpg',
    'Country-Excited': 'assert/images/country-excited.jpg',
    'Country-Calm': 'assert/images/country-calm.jpg',
  
    'Reggae-Happy': 'assert/images/reggae-happy.jpg',
    'Reggae-Sad': 'assert/images/reggae-sad.jpg',
    'Reggae-Energetic': 'assert/images/reggae-energetic.jpg',
    'Reggae-Relaxed': 'assert/images/reggae-relaxed.jpg',
    'Reggae-Melancholic': 'assert/images/reggae-melancholic.jpg',
    'Reggae-Excited': 'assert/images/reggae-excited.jpg',
    'Reggae-Calm': 'assert/images/reggae-calm.jpg',
  
    'Blues-Happy': 'assert/images/blues-happy.jpg',
    'Blues-Sad': 'assert/images/blues-sad.jpg',
    'Blues-Energetic': 'assert/images/blues-energetic.jpg',
    'Blues-Relaxed': 'assert/images/blues-relaxed.jpg',
    'Blues-Melancholic': 'assert/images/blues-melancholic.jpg',
    'Blues-Excited': 'assert/images/blues-excited.jpg',
    'Blues-Calm': 'assert/images/blues-calm.jpg',
  
    'Metal-Happy': 'assert/images/metal-happy.jpg',
    'Metal-Sad': 'assert/images/metal-sad.jpg',
    'Metal-Energetic': 'assert/images/metal-energetic.jpg',
    'Metal-Relaxed': 'assert/images/metal-relaxed.jpg',
    'Metal-Melancholic': 'assert/images/metal-melancholic.jpg',
    'Metal-Excited': 'assert/images/metal-excited.jpg',
    'Metal-Calm': 'assert/images/metal-calm.jpg',
  };
  
  
  export const genres = [
    'Pop',
    'Rock',
    'Jazz',
    'Classical',
    'Hip Hop',
    'Electronic',
    'Country',
    'Reggae',
    'Blues',
    'Metal',
  ];
  
  export const moods = [
    'Happy',
    'Sad',
    'Energetic',
    'Relaxed',
    'Melancholic',
    'Excited',
    'Calm',
  ];
  